name: Continuous Integration

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-24.04
    name: Erlang ${{matrix.otp}} / rebar ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['26', '27']
        rebar3: ['3']
        deps: ['grisp']
        # latest rebar3 versions that do not give problems with selected OTPs
        include:
          - otp: '24'
            rebar3: '3.23.0'
          - otp: '25'
            rebar3: '3.24.0'
    steps:

      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - name: Install GRiSP Plugin
        run: |
          mkdir -p ${HOME}/.config/rebar3/
          echo "{plugins, [rebar3_hex,rebar3_grisp]}." > ${HOME}/.config/rebar3/rebar.config
          rebar3 update

      - name: Generate Dummy Project
        run: |
          rebar3 grisp configure -i false --otp_version="=${{matrix.otp}}" --dest="_deploy"
          mkdir robot/_deploy
          sed -i 's/grisp/${{matrix.deps}}/g' robot/src/robot.app.src
          sed -i '/{deps, \[/,/\]}.*/{
          N
          N
          s/{deps, \[\n[[:space:]]*grisp\n\]}.*/{deps, [${{matrix.deps}}]}./
          }' robot/rebar.config
          cat robot/rebar.config

      - uses: actions/cache@v4
        env:
          cache-name: rebar3
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ci-${{runner.os}}-${{env.cache-name}}-otp_${{matrix.otp}}-rebar_${{matrix.rebar3}}-${{hashFiles('rebar.lock')}}
          restore-keys: |
            ci-${{runner.os}}-${{env.cache-name}}-otp_${{matrix.otp}}-rebar_${{matrix.rebar3}}
            ci-${{runner.os}}-${{env.cache-name}}-otp_${{matrix.otp}}

      - name: Compile
        run: rebar3 do clean, compile

      - name: Try to Deploy
        id: deploy
        continue-on-error: true
        working-directory: robot
        run: |
          rebar3 grisp deploy

      - name: Create GitHub Issue on Deploy Failure
        if: steps.deploy.outcome == 'failure'
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/grisp/rebar3_grisp/issues \
            -d "{\"title\":\"Deploy test failed for OTP-${{ matrix.otp }}\",\"body\":\"OTP Version: ${{ matrix.otp }}\nWorkflow: https://github.com/grisp/rebar3_grisp/actions/runs/${{ github.run_id }}\",\"labels\":[\"bug\"]}"
            exit 1
