name: Deployment Test
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
        matrix:
            include:
            - { otp: '27', rebar3: '3', deps: 'grisp' }
            - { otp: '26', rebar3: '3', deps: 'grisp' }
            - { otp: '24', rebar3: '3.23.0', deps: 'grisp' }
            - { otp: '25', rebar3: '3.24.0', deps: 'grisp' }
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}
      - name: Install GRiSP Plugin
        run: |
          mkdir -p ${HOME}/.config/rebar3/
          echo "{plugins, [rebar3_hex,rebar3_grisp]}." > ${HOME}/.config/rebar3/rebar.config
          rebar3 update
      - name: Generate Dummy Project
        run: |
          rebar3 grisp configure -i false --otp_version="=${{ matrix.otp }}" --dest="_deploy"
          mkdir robot/_deploy
          sed -i 's/grisp/${{ matrix.deps }}/g' robot/src/robot.app.src
          sed -i '/{deps, \[/,/\]}.*/{
          N
          N
          s/{deps, \[\n[[:space:]]*grisp\n\]}.*/{deps, [${{ matrix.deps }}]}./
          }' robot/rebar.config
          cat robot/rebar.config
      - name: Checkout repository into robot/_checkouts
        uses: actions/checkout@v4
        with:
            path: robot/_checkouts
      - name: Build OTP
        id: build
        working-directory: robot
        continue-on-error: true
        run: |
          sed -i '/{grisp, \[/a\
          '"{build, [{toolchain, [{directory, \"/grisp2-rtems-toolchain\"}]}]}," rebar.config
          cat rebar.config
          rebar3 grisp build --tar
          PKG_NAME=$(ls _grisp/grisp2/otp/${{matrix.otp}}/package)
          echo "pkg_name=$PKG_NAME" >> $GITHUB_ENV
      - name: Try to Deploy
        id: deploy
        if: ${{ steps.build.outcome == 'success' }}
        continue-on-error: true
        working-directory: robot
        run: |
          rebar3 grisp deploy
      - name: Create GitHub Issue on Failure
        if: ${{steps.build.outcome == 'failure' || steps.deploy.outcome == 'failure' }}
        run: |
            curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Fantarina/rebar3_grisp/issues \
            -d "{\"title\":\"Deploy test failed for OTP-${{ matrix.otp }}\",\"body\":\"Final deployment with rebar3_grisp plugin failed\nOTP Version: ${{ matrix.otp }}\nApplications: [${{ matrix.deps }}]\nWorkflow: https://github.com/Fantarina/rebar3_grisp/actions/runs/${{ github.run_id }}\",\"labels\":[\"bug\"]}"
            exit 1
